### ISSUE TITLE
JobResponse "error" is not String.

### ISSUE THREAD

**Issue by JTieman** [impinj/itemsense-java#10]
com.impinj.itemsense.client.coordinator.job.JobResponse does not define errors correctly.  Below is a a populated "errors" excerpt from the /control/v1/jobs/show response body json:

"errors": [
      {
        "time": "2016-06-15T05:49:15.514Z[GMT]",
        "message": "Could not detect job progress, possibly dead or in a bad state : Heartbeat Timed Out"
      },
      {
        "time": "2016-06-15T05:50:23.641Z[GMT]",
        "message": "Error publishing state to JobInstance : Initialization error: An error occurred while connecting to the reader (192.168.15.16): "
      },
      {
        "time": "2016-06-15T05:51:20.618Z[GMT]",
        "message": "Error publishing state to JobInstance : Initialization error: An error occurred while connecting to the reader (192.168.15.16): "
      },
      {
        "time": "2016-06-15T05:52:20.626Z[GMT]",
        "message": "Error publishing state to JobInstance : Initialization error: An error occurred while connecting to the reader (192.168.15.16): "
      },
      {
        "time": "2016-06-15T05:52:20.797Z[GMT]",
        "message": "Job was unable to start within the maximum number of start attempts (4) : Failed job"
      }
    ],

**Comment by natke** [comment]
Hi @JTieman, this issue should have been fixed now.
